CUR_MKFILE=$(abspath $(lastword $(MAKEFILE_LIST)))
SYNX_DEVICETREE_ROOT=$(dir $(CUR_MKFILE))
ifneq ($(KERNAL_HEADER_DIR),)
SYNX_KERNEL_ROOT=$(KERNAL_HEADER_DIR)
else
SYNX_KERNEL_ROOT=$(SYNX_DEVICETREE_ROOT)/../../opensource/synx-kernel
endif

KBUILD_OPTIONS += SYNX_DEVICETREE_ROOT=$(SYNX_DEVICETREE_ROOT)
KBUILD_OPTIONS += KBUILD_DTC_INCLUDE=$(SYNX_KERNEL_ROOT)
KBUILD_OPTIONS += KBUILD_EXTMOD_DTS=.
KBUILD_OPTIONS += KERNEL_ROOT=$(ROOT_DIR)/$(KERNEL_DIR)
KBUILD_OPTIONS += MODNAME=synx-devicetree

all: dtbs

dtbs:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) dtbs $(KBUILD_OPTIONS)

modules_install:
	$(MAKE) M=$(M) -C $(KERNEL_SRC) modules_install

clean:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) clean
